[package]
name = "library"
version = "0.1.0"
authors = ["RyotaBannai <ryotala0528@gmail.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
permutohedron = "=0.2.4"
superslice = "=1.0.0"
itertools = "=0.9.0"
itertools-num = "=0.1.3"
maplit = "=1.0.2"
either = "=1.5.3"